### ISSUE TITLE
Difference between OneShot and  WifeorWifi?

### ISSUE THREAD

**Issue by ghost** [5hojib/Wifeee#1]
Code looks exactly the same. What's the difference?

Here is the repo link. https://github.com/drygdryg/OneShot

**Comment by 5hojib** [comment]
> Code looks exactly the same. What's the difference?
> 
> Here is the repo link. https://github.com/drygdryg/OneShot

I just cloned this, I am not any programmer! Just renamed for fun with friends! By the way, I have deployed your group manager bot in heroku, it's not worked

**Comment by ghost** [comment]
> I just cloned this, I am not any programmer! Just renamed for fun with friends! By the way, I have deployed your group manager bot in heroku, it's not worked

It should work, maybe you forgot to add some environment variables? Works fine for me. 🤷‍♂️

**Comment by 5hojib** [comment]
> 
> > I just cloned this, I am not any programmer! Just renamed for fun with friends! By the way, I have deployed your group manager bot in heroku, it's not worked
> 
> It should work, maybe you forgot to add some environment variables? Works fine for me. 🤷‍♂️
> 

Maybe I used wrong mdb URI, if I use wrong, it's should at least reply after press start button right?

**Comment by ghost** [comment]
> Maybe I used wrong mdb URI, if I use wrong, it's should at least reply after press start button right?

No, it won't even start. Nezuko fetches sudoers from Mdb before starting client if I remember correctly. It will just stop after returning error.

**Comment by 5hojib** [comment]
> 
> > Maybe I used wrong mdb URI, if I use wrong, it's should at least reply after press start button right?
> 
> No, it won't even start. Nezuko fetches sudoers from Mdb before starting client if I remember correctly. It will just stop after returning error.

Thank you sir!

**Comment by 5hojib** [comment]
> 
> > Maybe I used wrong mdb URI, if I use wrong, it's should at least reply after press start button right?
> 
> No, it won't even start. Nezuko fetches sudoers from Mdb before starting client if I remember correctly. It will just stop after returning error.

You from Bangladesh?!?

**Comment by 5hojib** [comment]
Z
